### ISSUE TITLE
after applying this behavior, AR::getDirtyAttributes() becoms unreilable.

### ISSUE THREAD

**Issue by haolian9** [paulzi/yii2-json-behavior#2]
Since AR::getDirtyAttributes() relys on AR::_oldAttributes and AR::_attributes, But this Behavior just controll AR::_attributes.

Surelly It works fine when reading/writing, But this may cause some unexpected bug.

**Comment by paulzi** [comment]
I added a few tests:
https://github.com/paulzi/yii2-json-behavior/blob/82fcf2738f93508a051001f0f2a5bf01a7badb44/tests/BehaviorTest.php#L306-L321
One of this is testing `getDirtyAttributes()`. This method works as soon on after `encode()` attribute. That is, when you save the model, if the json attribute has not been changed, `getDirtyAttributes()` and `_oldAttributes` work correctly.
However, a direct call `getDirtyAttributes()` (out of the saving procedures), will issue all the time that the attribute "dirty". Fixed this behavior is not possible in Yii, because no event like `beforeCheckDirty()/afterCheckDirty()`, or as long as in php magic method `__equal()` appears:
https://bugs.php.net/bug.php?id=25772

**Comment by cronfy** [comment]
My application relies on `getDirtyAttributes()`. I need it to provide appropriate information whether attribute was changed or not.

To solve this in my application I override `getDirtyAttriburtes()` function in the model that has `JsonBehavior` like this:

```
public function getDirtyAttributes($names = null)
{
    $jsonAttributes = [];

    // get json attributes
    foreach ($this->behaviors as $behavior) {
        if (is_a($behavior, JsonBehavior::class)) {
            $jsonAttributes = array_merge($jsonAttributes, $behavior->attributes);
        }
    }

    // from native getDirtyAttributes()
    if ($names === null) {
        $names = $this->attributes();
    }

    $jsonCheckDirty = [];
    // remember which json attributes we want to check
    foreach ($names as $k => $name) {
        if (in_array($name, $jsonAttributes)) {
            $jsonCheckDirty[] = $name;
            unset($names[$k]); // exclude json attributes from native check
        }
    }

    // native check
    $dirtyAttributes = parent::getDirtyAttributes($names);

    $jsonDirty = [];
    // check whether json attributes were changed
    foreach ($jsonCheckDirty as $jsonAttribute) {
        if (isset($this->oldAttributes[$jsonAttribute])) {
            if (((string) $this->$jsonAttribute) !== $this->oldAttributes[$jsonAttribute]) {
                $jsonDirty[] = $jsonAttribute;
            }
        } else {
            if ((string) $this->$jsonAttribute) {
                $jsonDirty[] = $jsonAttribute;
            }
        }
    }

    // merge native result with our result
    foreach ($jsonDirty as $jsonAttribute) {
        $dirtyAttributes[$jsonAttribute] = $this->$jsonAttribute;
    }

    return $dirtyAttributes;
}
```

@paulzi could you maybe add this to some howto?

**Comment by paulzi** [comment]
@cronfy , https://github.com/paulzi/yii2-json-behavior#how-to
