### ISSUE TITLE
Empty array converts to null

### ISSUE THREAD

**Issue by mixlion** [paulzi/yii2-json-behavior#6]
If an attribute with the json behavior has an empty array as a value, it converts to the `null`, instead of empty json array `[]` or object `{}`.
Example: 
```php
$model = new SomeModel();
$model->jsonBehaviorField = [];
$model->save(); 
```

Got SQL: `INSERT INTO table (jsonBehaviorField) VALUES (null);`
Expected: `INSERT INTO table (jsonBehaviorField) VALUES ('[]');`

It would be great to have a behavior configuration what empty array converts to: null, empty json array or empty json object.

**Comment by paulzi** [comment]
@mixlion I need more information on this issue, because I can not reproduce the problem. Namely, the type and version of the database, whether the validators are executed before saving.
In theory, before you save model, it checks and writes null:
https://github.com/paulzi/yii2-json-behavior/blob/20a803b71b1f7d7185dac5b7b2b90cc472a36d59/src/JsonBehavior.php#L64

Additionally, I do not recommend overwrite the value of the field directly, since after the initialization of the behavior it is converted to a JsonField. And if you do `$model->jsonBehaviorField = [];` then the field is changed to an array, and this will then generate errors `indirect modification of overloaded property`:
```php
$model->jsonBehaviorField = [];
$model->jsonBehaviorField->test = 1; // throw exception
```
I recommend doing this:
```php
$model->jsonBehaviorField->set([]);
$model->jsonBehaviorField['test'] = 1; // ok
```

**Comment by mixlion** [comment]
> In theory, before you save model, it checks and writes null:

Yes, it works as you describe, but I need to write to the database exactly what passed to the field: empty array or empty object.

Table schema:
```sql
CREATE TABLE test(
  id serial PRIMARY KEY,
  field JSON
);
```

Model:
```php
class Test extends \yii\db\ActiveRecord
{
  public function behaviors()
  {
    return [
      [
        'attributes' => ['field'],
        'class' => \paulzi\jsonBehavior\JsonBehavior::className()
      ]
    ];
  }
}
```

Test to reproduce:
```php
$model = new Test();
$model->field->set([]);
$model->save();
```

Need record in database with `field = []`, but have `field = NULL`.

Database used: PostgreSQL 9.6.4

**Comment by paulzi** [comment]
Do you want to add behavior field `$emptyValue`, with options: null|string ('{}', '[]')?

**Comment by mixlion** [comment]
Yes, it would be great.
